# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  get-correct-name:
    runs-on: ubuntu-latest
    steps:
      - name: step name
        run: echo kdesi cosi
    outputs:
      name: ${{ contains(github.sha, '5') && 'name one' || 'name two' }}  
      name2: ${{ contains(github.sha, '1232') && 'true 1232' || 'f 1232' }}  
  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: get-correct-name

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ${{needs.get-correct-name.outputs.name}},
          echo ${{needs.get-correct-name.outputs.name2}},
          echo sha is ${{github.sha}}
          echo test, and deploy your project.
          
  telegram-notif:
    name: telegram notif
    needs: [get-correct-name]
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit ${{needs.get-correct-name.outputs.name}}:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}} 
            
            ${{needs.get-correct-name.outputs.name2}}
          
